name: main

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version from upstream (optional)"
        required: false
        default: ""

concurrency:
  group: mirror
  cancel-in-progress: false

jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ensure tags & full history are available

      - name: Wait for PyPI propagation
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: sleep 30

      - name: Extract version from payload (if any)
        id: payload
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          echo "PAYLOAD_VERSION=${{ github.event.client_payload.version }}" >> "$GITHUB_ENV"
          echo "Payload version: ${{ github.event.client_payload.version }}"

      - name: set git config
        run: |
          git config --global user.email "release-bot@example.com"
          git config --global user.name "Release Bot"

      # Let sync.sh prefer $PAYLOAD_VERSION if set, else fall back to PyPI latest
      - name: sync mirror
        run: ./sync.sh
        env:
          PAYLOAD_VERSION: ${{ env.PAYLOAD_VERSION }}

      - name: check for unpushed commits
        id: check_unpushed
        run: |
          # Ensure origin/main exists locally
          git fetch origin main --tags
          if [ -z "$(git log origin/main..HEAD)" ]; then
            echo "changes_exist=false" >> $GITHUB_ENV
            echo "No unpushed commits found."
          else
            echo "changes_exist=true" >> $GITHUB_ENV
            echo "Unpushed commits found."
          fi

      - name: push changes if they exist
        if: env.changes_exist == 'true'
        run: |
          git push origin HEAD:refs/heads/main
          git push origin --tags

      - name: create release on new tag if new changes exist
        if: env.changes_exist == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Prefer the tag we just created in sync.sh; fall back to "most recent tag"
          TAG_NAME="${PAYLOAD_VERSION:+v$PAYLOAD_VERSION}"
          if [ -z "$TAG_NAME" ]; then
            TAG_NAME="$(git describe --tags "$(git rev-list --tags --max-count=1)")"
          fi
          echo "Releasing tag: $TAG_NAME"
          gh release create "$TAG_NAME" \
            --title "$TAG_NAME" \
            --notes "See: https://github.com/simone-viozzi/rusty-todo-md/releases/tag/${TAG_NAME#v}" \
            --latest
